tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "caskroom/versions"
tap "caskroom/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-drivers"

brew "awscli"
brew "gpg"
brew "stern"
brew "kubernetes-cli"
brew "kubernetes-helm"
brew "kubectx"
brew "zsh"
brew "golang"
brew "antigen"
brew "htop"
brew "coreutils"
brew "jenv"
brew "jq"

cask "iterm2"
cask "jetbrains-toolbox"
cask "sublime-text"
cask "docker"
cask "google-chrome"
cask "franz"
cask "font-inconsolata-dz-for-powerline"
cask "zoomus"

